// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/florinel-chis/gophercrm/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// The interface (aeo.Executor) is deliberately NOT asserted here: the aeo
// package's own in-package tests import this package, so importing aeo back
// would be an import cycle. Every method below is written against the pinned
// signature instead.

// AEOExecutor is an autogenerated mock type for the aeo.Executor type
type AEOExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, run, prompts, profile
func (_m *AEOExecutor) Execute(ctx context.Context, run *models.AEORun, prompts []models.AEOPrompt, profile *models.AEOProfile) error {
	ret := _m.Called(ctx, run, prompts, profile)
	return ret.Error(0)
}

// NewAEOExecutor creates a new instance of AEOExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAEOExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *AEOExecutor {
	mock := &AEOExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
