// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	aeo "github.com/florinel-chis/gophercrm/internal/aeo"
	mock "github.com/stretchr/testify/mock"
)

// The interface (aeo.Provider) is deliberately NOT asserted here: the aeo
// package's own in-package tests import this package, so importing aeo for an
// assertion would risk an import cycle. Note that aeo.ProviderAnswer is part of
// the Query signature, so this file does import aeo for the type alone — the
// aeo package must therefore keep its own tests free of internal/mocks, or use
// an external test package.

// AEOProvider is an autogenerated mock type for the aeo.Provider type
type AEOProvider struct {
	mock.Mock
}

// Name provides a mock function with no fields
func (_m *AEOProvider) Name() string {
	ret := _m.Called()
	return ret.String(0)
}

// Model provides a mock function with no fields
func (_m *AEOProvider) Model() string {
	ret := _m.Called()
	return ret.String(0)
}

// Query provides a mock function with given fields: ctx, prompt
func (_m *AEOProvider) Query(ctx context.Context, prompt string) (aeo.ProviderAnswer, error) {
	ret := _m.Called(ctx, prompt)

	var r0 aeo.ProviderAnswer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(aeo.ProviderAnswer)
	}
	return r0, ret.Error(1)
}

// NewAEOProvider creates a new instance of AEOProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAEOProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AEOProvider {
	mock := &AEOProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
