// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	time "time"

	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.AEORepository = (*AEORepository)(nil)

// AEORepository is an autogenerated mock type for the AEORepository type
type AEORepository struct {
	mock.Mock
}

// GetProfile provides a mock function with no fields
func (_m *AEORepository) GetProfile() (*models.AEOProfile, error) {
	ret := _m.Called()

	var r0 *models.AEOProfile
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEOProfile)
	}
	return r0, ret.Error(1)
}

// UpsertProfile provides a mock function with given fields: profile
func (_m *AEORepository) UpsertProfile(profile *models.AEOProfile) error {
	ret := _m.Called(profile)
	return ret.Error(0)
}

// CreatePrompt provides a mock function with given fields: prompt
func (_m *AEORepository) CreatePrompt(prompt *models.AEOPrompt) error {
	ret := _m.Called(prompt)
	return ret.Error(0)
}

// GetPromptByID provides a mock function with given fields: id
func (_m *AEORepository) GetPromptByID(id uint) (*models.AEOPrompt, error) {
	ret := _m.Called(id)

	var r0 *models.AEOPrompt
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEOPrompt)
	}
	return r0, ret.Error(1)
}

// UpdatePrompt provides a mock function with given fields: prompt
func (_m *AEORepository) UpdatePrompt(prompt *models.AEOPrompt) error {
	ret := _m.Called(prompt)
	return ret.Error(0)
}

// DeletePrompt provides a mock function with given fields: id
func (_m *AEORepository) DeletePrompt(id uint) error {
	ret := _m.Called(id)
	return ret.Error(0)
}

// ListPrompts provides a mock function with given fields: activeOnly, offset, limit, sortBy, sortOrder
func (_m *AEORepository) ListPrompts(activeOnly bool, offset int, limit int, sortBy string, sortOrder string) ([]models.AEOPrompt, error) {
	ret := _m.Called(activeOnly, offset, limit, sortBy, sortOrder)

	var r0 []models.AEOPrompt
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOPrompt)
	}
	return r0, ret.Error(1)
}

// CountPrompts provides a mock function with given fields: activeOnly
func (_m *AEORepository) CountPrompts(activeOnly bool) (int64, error) {
	ret := _m.Called(activeOnly)

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// ListActivePrompts provides a mock function with no fields
func (_m *AEORepository) ListActivePrompts() ([]models.AEOPrompt, error) {
	ret := _m.Called()

	var r0 []models.AEOPrompt
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOPrompt)
	}
	return r0, ret.Error(1)
}

// ExistsByTextInsensitive provides a mock function with given fields: text, excludeID
func (_m *AEORepository) ExistsByTextInsensitive(text string, excludeID uint) (bool, error) {
	ret := _m.Called(text, excludeID)

	var r0 bool
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(bool)
	}
	return r0, ret.Error(1)
}

// CreateRun provides a mock function with given fields: run
func (_m *AEORepository) CreateRun(run *models.AEORun) error {
	ret := _m.Called(run)
	return ret.Error(0)
}

// GetRunByID provides a mock function with given fields: id
func (_m *AEORepository) GetRunByID(id uint) (*models.AEORun, error) {
	ret := _m.Called(id)

	var r0 *models.AEORun
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEORun)
	}
	return r0, ret.Error(1)
}

// UpdateRun provides a mock function with given fields: run
func (_m *AEORepository) UpdateRun(run *models.AEORun) error {
	ret := _m.Called(run)
	return ret.Error(0)
}

// ListRuns provides a mock function with given fields: offset, limit, sortBy, sortOrder
func (_m *AEORepository) ListRuns(offset int, limit int, sortBy string, sortOrder string) ([]models.AEORun, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder)

	var r0 []models.AEORun
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEORun)
	}
	return r0, ret.Error(1)
}

// CountRuns provides a mock function with no fields
func (_m *AEORepository) CountRuns() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// GetLatestRun provides a mock function with no fields
func (_m *AEORepository) GetLatestRun() (*models.AEORun, error) {
	ret := _m.Called()

	var r0 *models.AEORun
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEORun)
	}
	return r0, ret.Error(1)
}

// CountRunsByStatus provides a mock function with given fields: status
func (_m *AEORepository) CountRunsByStatus(status string) (int64, error) {
	ret := _m.Called(status)

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// MarkStaleRunsFailed provides a mock function with given fields: cutoff
func (_m *AEORepository) MarkStaleRunsFailed(cutoff time.Time) (int64, error) {
	ret := _m.Called(cutoff)

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// CreateAnswerWithCitations provides a mock function with given fields: answer, citations
func (_m *AEORepository) CreateAnswerWithCitations(answer *models.AEOAnswer, citations []models.AEOCitation) error {
	ret := _m.Called(answer, citations)
	return ret.Error(0)
}

// ListAnswersByPrompt provides a mock function with given fields: promptID, runID, offset, limit
func (_m *AEORepository) ListAnswersByPrompt(promptID uint, runID *uint, offset int, limit int) ([]models.AEOAnswer, error) {
	ret := _m.Called(promptID, runID, offset, limit)

	var r0 []models.AEOAnswer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOAnswer)
	}
	return r0, ret.Error(1)
}

// CountAnswersByPrompt provides a mock function with given fields: promptID, runID
func (_m *AEORepository) CountAnswersByPrompt(promptID uint, runID *uint) (int64, error) {
	ret := _m.Called(promptID, runID)

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// ListAnswersByRun provides a mock function with given fields: runID
func (_m *AEORepository) ListAnswersByRun(runID uint) ([]models.AEOAnswer, error) {
	ret := _m.Called(runID)

	var r0 []models.AEOAnswer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOAnswer)
	}
	return r0, ret.Error(1)
}

// ListAnswerFacts provides a mock function with given fields: from, to
func (_m *AEORepository) ListAnswerFacts(from time.Time, to time.Time) ([]models.AEOAnswerFact, error) {
	ret := _m.Called(from, to)

	var r0 []models.AEOAnswerFact
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOAnswerFact)
	}
	return r0, ret.Error(1)
}

// PromptVisibility provides a mock function with given fields: from, to, promptIDs
func (_m *AEORepository) PromptVisibility(from time.Time, to time.Time, promptIDs []uint) (map[uint]models.AEOPromptVisibility, error) {
	ret := _m.Called(from, to, promptIDs)

	var r0 map[uint]models.AEOPromptVisibility
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(map[uint]models.AEOPromptVisibility)
	}
	return r0, ret.Error(1)
}

// CitationDomainStats provides a mock function with given fields: from, to
func (_m *AEORepository) CitationDomainStats(from time.Time, to time.Time) ([]models.AEOCitationAggRow, error) {
	ret := _m.Called(from, to)

	var r0 []models.AEOCitationAggRow
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOCitationAggRow)
	}
	return r0, ret.Error(1)
}

// CountAnswersInRange provides a mock function with given fields: from, to
func (_m *AEORepository) CountAnswersInRange(from time.Time, to time.Time) (int64, int64, error) {
	ret := _m.Called(from, to)

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}

	var r1 int64
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1, ret.Error(2)
}

// CountAnswersWithCitations provides a mock function with given fields: from, to
func (_m *AEORepository) CountAnswersWithCitations(from time.Time, to time.Time) (int64, error) {
	ret := _m.Called(from, to)

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// WithTx provides a mock function with given fields: tx
func (_m *AEORepository) WithTx(tx *gorm.DB) repository.AEORepository {
	ret := _m.Called(tx)

	var r0 repository.AEORepository
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(repository.AEORepository)
	}
	return r0
}

// NewAEORepository creates a new instance of AEORepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAEORepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AEORepository {
	mock := &AEORepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
