// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	models "github.com/florinel-chis/gophercrm/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// The interface is deliberately NOT asserted here: internal/service's own
// in-package tests import this package, so importing service back would be an
// import cycle. The compile-time check lives in the handler tests instead.

// AEOService is an autogenerated mock type for the AEOService type
type AEOService struct {
	mock.Mock
}

// GetProfile provides a mock function with no fields
func (_m *AEOService) GetProfile() (*models.AEOProfile, error) {
	ret := _m.Called()

	var r0 *models.AEOProfile
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEOProfile)
	}
	return r0, ret.Error(1)
}

// SaveProfile provides a mock function with given fields: profile
func (_m *AEOService) SaveProfile(profile *models.AEOProfile) (*models.AEOProfile, error) {
	ret := _m.Called(profile)

	var r0 *models.AEOProfile
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEOProfile)
	}
	return r0, ret.Error(1)
}

// ListPrompts provides a mock function with given fields: from, to, activeOnly, offset, limit, sortBy, sortOrder
func (_m *AEOService) ListPrompts(from time.Time, to time.Time, activeOnly bool, offset int, limit int, sortBy string, sortOrder string) ([]models.AEOPrompt, int64, error) {
	ret := _m.Called(from, to, activeOnly, offset, limit, sortBy, sortOrder)

	var r0 []models.AEOPrompt
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOPrompt)
	}

	var r1 int64
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1, ret.Error(2)
}

// CreatePrompts provides a mock function with given fields: texts, createdByID
func (_m *AEOService) CreatePrompts(texts []string, createdByID uint) ([]models.AEOPrompt, error) {
	ret := _m.Called(texts, createdByID)

	var r0 []models.AEOPrompt
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOPrompt)
	}
	return r0, ret.Error(1)
}

// UpdatePrompt provides a mock function with given fields: id, text, isActive
func (_m *AEOService) UpdatePrompt(id uint, text *string, isActive *bool) (*models.AEOPrompt, error) {
	ret := _m.Called(id, text, isActive)

	var r0 *models.AEOPrompt
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEOPrompt)
	}
	return r0, ret.Error(1)
}

// DeletePrompt provides a mock function with given fields: id
func (_m *AEOService) DeletePrompt(id uint) error {
	ret := _m.Called(id)
	return ret.Error(0)
}

// GeneratePrompts provides a mock function with given fields: ctx, count
func (_m *AEOService) GeneratePrompts(ctx context.Context, count int) ([]string, error) {
	ret := _m.Called(ctx, count)

	var r0 []string
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]string)
	}
	return r0, ret.Error(1)
}

// StartRun provides a mock function with given fields: ctx, trigger, triggeredByID
func (_m *AEOService) StartRun(ctx context.Context, trigger string, triggeredByID *uint) (*models.AEORun, error) {
	ret := _m.Called(ctx, trigger, triggeredByID)

	var r0 *models.AEORun
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEORun)
	}
	return r0, ret.Error(1)
}

// ReconcileRunningRuns provides a mock function with given fields:
func (_m *AEOService) ReconcileRunningRuns() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int64)
	}
	return r0, ret.Error(1)
}

// ListRuns provides a mock function with given fields: offset, limit, sortBy, sortOrder
func (_m *AEOService) ListRuns(offset int, limit int, sortBy string, sortOrder string) ([]models.AEORun, int64, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder)

	var r0 []models.AEORun
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEORun)
	}

	var r1 int64
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1, ret.Error(2)
}

// GetRun provides a mock function with given fields: id
func (_m *AEOService) GetRun(id uint) (*models.AEORun, error) {
	ret := _m.Called(id)

	var r0 *models.AEORun
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEORun)
	}
	return r0, ret.Error(1)
}

// GetPromptAnswers provides a mock function with given fields: promptID, runID, offset, limit
func (_m *AEOService) GetPromptAnswers(promptID uint, runID *uint, offset int, limit int) ([]models.AEOAnswer, int64, error) {
	ret := _m.Called(promptID, runID, offset, limit)

	var r0 []models.AEOAnswer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOAnswer)
	}

	var r1 int64
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1, ret.Error(2)
}

// Dashboard provides a mock function with given fields: from, to
func (_m *AEOService) Dashboard(from time.Time, to time.Time) (*models.AEODashboard, error) {
	ret := _m.Called(from, to)

	var r0 *models.AEODashboard
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEODashboard)
	}
	return r0, ret.Error(1)
}

// Citations provides a mock function with given fields: from, to
func (_m *AEOService) Citations(from time.Time, to time.Time) (*models.AEOCitationsReport, error) {
	ret := _m.Called(from, to)

	var r0 *models.AEOCitationsReport
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.AEOCitationsReport)
	}
	return r0, ret.Error(1)
}

// Providers provides a mock function with no fields
func (_m *AEOService) Providers() []models.AEOProviderStatus {
	ret := _m.Called()

	var r0 []models.AEOProviderStatus
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AEOProviderStatus)
	}
	return r0
}

// NewAEOService creates a new instance of AEOService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAEOService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AEOService {
	mock := &AEOService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
