// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// BulkOperationRepository is an autogenerated mock type for the BulkOperationRepository type
type BulkOperationRepository struct {
	mock.Mock
}

// Count provides a mock function with no fields
func (_m *BulkOperationRepository) Count() (int64, error) {
	ret := _m.Called()

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByUserID provides a mock function with given fields: userID
func (_m *BulkOperationRepository) CountByUserID(userID uint) (int64, error) {
	ret := _m.Called(userID)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (int64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) int64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: operation
func (_m *BulkOperationRepository) Create(operation *models.BulkOperation) error {
	ret := _m.Called(operation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BulkOperation) error); ok {
		r0 = rf(operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateItem provides a mock function with given fields: item
func (_m *BulkOperationRepository) CreateItem(item *models.BulkOperationItem) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BulkOperationItem) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *BulkOperationRepository) Delete(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *BulkOperationRepository) GetByID(id uint) (*models.BulkOperation, error) {
	ret := _m.Called(id)

	var r0 *models.BulkOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.BulkOperation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.BulkOperation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BulkOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDWithItems provides a mock function with given fields: id
func (_m *BulkOperationRepository) GetByIDWithItems(id uint) (*models.BulkOperation, error) {
	ret := _m.Called(id)

	var r0 *models.BulkOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.BulkOperation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.BulkOperation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BulkOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: userID, offset, limit
func (_m *BulkOperationRepository) GetByUserID(userID uint, offset int, limit int) ([]models.BulkOperation, error) {
	ret := _m.Called(userID, offset, limit)

	var r0 []models.BulkOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.BulkOperation, error)); ok {
		return rf(userID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.BulkOperation); ok {
		r0 = rf(userID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BulkOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(userID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItemsByOperationID provides a mock function with given fields: operationID
func (_m *BulkOperationRepository) GetItemsByOperationID(operationID uint) ([]models.BulkOperationItem, error) {
	ret := _m.Called(operationID)

	var r0 []models.BulkOperationItem
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.BulkOperationItem, error)); ok {
		return rf(operationID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.BulkOperationItem); ok {
		r0 = rf(operationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BulkOperationItem)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(operationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: offset, limit
func (_m *BulkOperationRepository) List(offset int, limit int) ([]models.BulkOperation, error) {
	ret := _m.Called(offset, limit)

	var r0 []models.BulkOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.BulkOperation, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.BulkOperation); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BulkOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: operation
func (_m *BulkOperationRepository) Update(operation *models.BulkOperation) error {
	ret := _m.Called(operation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BulkOperation) error); ok {
		r0 = rf(operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateItem provides a mock function with given fields: item
func (_m *BulkOperationRepository) UpdateItem(item *models.BulkOperationItem) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BulkOperationItem) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *BulkOperationRepository) UpdateStatus(id uint, status models.BulkOperationStatus) error {
	ret := _m.Called(id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, models.BulkOperationStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *BulkOperationRepository) WithTx(tx *gorm.DB) repository.BulkOperationRepository {
	ret := _m.Called(tx)

	var r0 repository.BulkOperationRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.BulkOperationRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.BulkOperationRepository)
		}
	}

	return r0
}

type mockConstructorTestingTNewBulkOperationRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBulkOperationRepository creates a new instance of BulkOperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBulkOperationRepository(t mockConstructorTestingTNewBulkOperationRepository) *BulkOperationRepository {
	mock := &BulkOperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}