// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// BulkRepository is an autogenerated mock type for the BulkRepository type
type BulkRepository struct {
	mock.Mock
}

// BulkCreateCustomers provides a mock function with given fields: customers
func (_m *BulkRepository) BulkCreateCustomers(customers []models.Customer) ([]models.Customer, []error) {
	ret := _m.Called(customers)

	var r0 []models.Customer
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.Customer) ([]models.Customer, []error)); ok {
		return rf(customers)
	}
	if rf, ok := ret.Get(0).(func([]models.Customer) []models.Customer); ok {
		r0 = rf(customers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.Customer) []error); ok {
		r1 = rf(customers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkCreateLeads provides a mock function with given fields: leads
func (_m *BulkRepository) BulkCreateLeads(leads []models.Lead) ([]models.Lead, []error) {
	ret := _m.Called(leads)

	var r0 []models.Lead
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.Lead) ([]models.Lead, []error)); ok {
		return rf(leads)
	}
	if rf, ok := ret.Get(0).(func([]models.Lead) []models.Lead); ok {
		r0 = rf(leads)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Lead)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.Lead) []error); ok {
		r1 = rf(leads)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkCreateTasks provides a mock function with given fields: tasks
func (_m *BulkRepository) BulkCreateTasks(tasks []models.Task) ([]models.Task, []error) {
	ret := _m.Called(tasks)

	var r0 []models.Task
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.Task) ([]models.Task, []error)); ok {
		return rf(tasks)
	}
	if rf, ok := ret.Get(0).(func([]models.Task) []models.Task); ok {
		r0 = rf(tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.Task) []error); ok {
		r1 = rf(tasks)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkCreateTickets provides a mock function with given fields: tickets
func (_m *BulkRepository) BulkCreateTickets(tickets []models.Ticket) ([]models.Ticket, []error) {
	ret := _m.Called(tickets)

	var r0 []models.Ticket
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.Ticket) ([]models.Ticket, []error)); ok {
		return rf(tickets)
	}
	if rf, ok := ret.Get(0).(func([]models.Ticket) []models.Ticket); ok {
		r0 = rf(tickets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.Ticket) []error); ok {
		r1 = rf(tickets)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkCreateUsers provides a mock function with given fields: users
func (_m *BulkRepository) BulkCreateUsers(users []models.User) ([]models.User, []error) {
	ret := _m.Called(users)

	var r0 []models.User
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.User) ([]models.User, []error)); ok {
		return rf(users)
	}
	if rf, ok := ret.Get(0).(func([]models.User) []models.User); ok {
		r0 = rf(users)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.User) []error); ok {
		r1 = rf(users)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkDeleteCustomers provides a mock function with given fields: ids
func (_m *BulkRepository) BulkDeleteCustomers(ids []uint) []error {
	ret := _m.Called(ids)

	var r0 []error
	if rf, ok := ret.Get(0).(func([]uint) []error); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// BulkDeleteLeads provides a mock function with given fields: ids
func (_m *BulkRepository) BulkDeleteLeads(ids []uint) []error {
	ret := _m.Called(ids)

	var r0 []error
	if rf, ok := ret.Get(0).(func([]uint) []error); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// BulkDeleteTasks provides a mock function with given fields: ids
func (_m *BulkRepository) BulkDeleteTasks(ids []uint) []error {
	ret := _m.Called(ids)

	var r0 []error
	if rf, ok := ret.Get(0).(func([]uint) []error); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// BulkDeleteTickets provides a mock function with given fields: ids
func (_m *BulkRepository) BulkDeleteTickets(ids []uint) []error {
	ret := _m.Called(ids)

	var r0 []error
	if rf, ok := ret.Get(0).(func([]uint) []error); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// BulkDeleteUsers provides a mock function with given fields: ids
func (_m *BulkRepository) BulkDeleteUsers(ids []uint) []error {
	ret := _m.Called(ids)

	var r0 []error
	if rf, ok := ret.Get(0).(func([]uint) []error); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// BulkUpdateCustomers provides a mock function with given fields: updates
func (_m *BulkRepository) BulkUpdateCustomers(updates []models.BulkUpdateItem) ([]models.Customer, []error) {
	ret := _m.Called(updates)

	var r0 []models.Customer
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) ([]models.Customer, []error)); ok {
		return rf(updates)
	}
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) []models.Customer); ok {
		r0 = rf(updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.BulkUpdateItem) []error); ok {
		r1 = rf(updates)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkUpdateLeads provides a mock function with given fields: updates
func (_m *BulkRepository) BulkUpdateLeads(updates []models.BulkUpdateItem) ([]models.Lead, []error) {
	ret := _m.Called(updates)

	var r0 []models.Lead
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) ([]models.Lead, []error)); ok {
		return rf(updates)
	}
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) []models.Lead); ok {
		r0 = rf(updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Lead)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.BulkUpdateItem) []error); ok {
		r1 = rf(updates)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkUpdateTasks provides a mock function with given fields: updates
func (_m *BulkRepository) BulkUpdateTasks(updates []models.BulkUpdateItem) ([]models.Task, []error) {
	ret := _m.Called(updates)

	var r0 []models.Task
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) ([]models.Task, []error)); ok {
		return rf(updates)
	}
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) []models.Task); ok {
		r0 = rf(updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.BulkUpdateItem) []error); ok {
		r1 = rf(updates)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkUpdateTickets provides a mock function with given fields: updates
func (_m *BulkRepository) BulkUpdateTickets(updates []models.BulkUpdateItem) ([]models.Ticket, []error) {
	ret := _m.Called(updates)

	var r0 []models.Ticket
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) ([]models.Ticket, []error)); ok {
		return rf(updates)
	}
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) []models.Ticket); ok {
		r0 = rf(updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.BulkUpdateItem) []error); ok {
		r1 = rf(updates)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// BulkUpdateUsers provides a mock function with given fields: updates
func (_m *BulkRepository) BulkUpdateUsers(updates []models.BulkUpdateItem) ([]models.User, []error) {
	ret := _m.Called(updates)

	var r0 []models.User
	var r1 []error
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) ([]models.User, []error)); ok {
		return rf(updates)
	}
	if rf, ok := ret.Get(0).(func([]models.BulkUpdateItem) []models.User); ok {
		r0 = rf(updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.BulkUpdateItem) []error); ok {
		r1 = rf(updates)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *BulkRepository) WithTx(tx *gorm.DB) repository.BulkRepository {
	ret := _m.Called(tx)

	var r0 repository.BulkRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.BulkRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.BulkRepository)
		}
	}

	return r0
}

type mockConstructorTestingTNewBulkRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBulkRepository creates a new instance of BulkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBulkRepository(t mockConstructorTestingTNewBulkRepository) *BulkRepository {
	mock := &BulkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}