// Code generated by mockery v2.53.4. DO NOT EDIT.
// Written by hand in the generated style, like the other repository mocks.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.CompanyRepository = (*CompanyRepository)(nil)

// CompanyRepository is a mock type for the CompanyRepository type
type CompanyRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: company
func (_m *CompanyRepository) Create(company *models.Company) error {
	ret := _m.Called(company)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Company) error); ok {
		r0 = rf(company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *CompanyRepository) GetByID(id uint) (*models.Company, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Company
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.Company)
	}
	return r0, ret.Error(1)
}

// Update provides a mock function with given fields: company
func (_m *CompanyRepository) Update(company *models.Company) error {
	ret := _m.Called(company)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	return ret.Error(0)
}

// Delete provides a mock function with given fields: id
func (_m *CompanyRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	return ret.Error(0)
}

// List provides a mock function with given fields: offset, limit, search, sortBy, sortOrder
func (_m *CompanyRepository) List(offset int, limit int, search string, sortBy string, sortOrder string) ([]models.Company, int64, error) {
	ret := _m.Called(offset, limit, search, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Company
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Company)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// ExistsByDomain provides a mock function with given fields: domain, excludeID
func (_m *CompanyRepository) ExistsByDomain(domain string, excludeID uint) (bool, error) {
	ret := _m.Called(domain, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByDomain")
	}

	return ret.Get(0).(bool), ret.Error(1)
}

// UnlinkLeads provides a mock function with given fields: companyID
func (_m *CompanyRepository) UnlinkLeads(companyID uint) error {
	ret := _m.Called(companyID)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkLeads")
	}

	return ret.Error(0)
}

// UnlinkCustomers provides a mock function with given fields: companyID
func (_m *CompanyRepository) UnlinkCustomers(companyID uint) error {
	ret := _m.Called(companyID)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkCustomers")
	}

	return ret.Error(0)
}

// ListCustomers provides a mock function with given fields: companyID, offset, limit
func (_m *CompanyRepository) ListCustomers(companyID uint, offset int, limit int) ([]models.Customer, int64, error) {
	ret := _m.Called(companyID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCustomers")
	}

	var r0 []models.Customer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Customer)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// ListLeads provides a mock function with given fields: companyID, ownerID, offset, limit
func (_m *CompanyRepository) ListLeads(companyID uint, ownerID *uint, offset int, limit int) ([]models.Lead, int64, error) {
	ret := _m.Called(companyID, ownerID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListLeads")
	}

	var r0 []models.Lead
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Lead)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// WithTx provides a mock function with given fields: tx
func (_m *CompanyRepository) WithTx(tx *gorm.DB) repository.CompanyRepository {
	_m.Called(tx)
	return _m
}

// NewCompanyRepository creates a new instance of CompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyRepository {
	mock := &CompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
