// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ConfigurationRepository is an autogenerated mock type for the ConfigurationRepository type
type ConfigurationRepository struct {
	mock.Mock
}

// BulkUpsert provides a mock function with given fields: configs
func (_m *ConfigurationRepository) BulkUpsert(configs []models.Configuration) error {
	ret := _m.Called(configs)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.Configuration) error); ok {
		r0 = rf(configs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: config
func (_m *ConfigurationRepository) Create(config *models.Configuration) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Configuration) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: key
func (_m *ConfigurationRepository) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *ConfigurationRepository) GetAll() ([]models.Configuration, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Configuration, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Configuration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCategory provides a mock function with given fields: category
func (_m *ConfigurationRepository) GetByCategory(category models.ConfigurationCategory) ([]models.Configuration, error) {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategory")
	}

	var r0 []models.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ConfigurationCategory) ([]models.Configuration, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(models.ConfigurationCategory) []models.Configuration); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(models.ConfigurationCategory) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByKey provides a mock function with given fields: key
func (_m *ConfigurationRepository) GetByKey(key string) (*models.Configuration, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 *models.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Configuration, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Configuration); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitializeDefaults provides a mock function with no fields
func (_m *ConfigurationRepository) InitializeDefaults() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeDefaults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: config
func (_m *ConfigurationRepository) Update(config *models.Configuration) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Configuration) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigurationRepository creates a new instance of ConfigurationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationRepository {
	mock := &ConfigurationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
