// Code generated by mockery v2.53.4. DO NOT EDIT.
// Modified to add missing interface methods.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.CustomerRepository = (*CustomerRepository)(nil)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// Count provides a mock function with no fields
func (_m *CustomerRepository) Count() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: customer
func (_m *CustomerRepository) Create(customer *models.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CustomerRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEmail provides a mock function with given fields: email
func (_m *CustomerRepository) GetByEmail(email string) (*models.Customer, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Customer, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Customer); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CustomerRepository) GetByID(id uint) (*models.Customer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Customer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDWithPreloads provides a mock function with given fields: id, preloads
func (_m *CustomerRepository) GetByIDWithPreloads(id uint, preloads ...string) (*models.Customer, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithPreloads")
	}

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, ...string) (*models.Customer, error)); ok {
		return rf(id, preloads...)
	}
	if rf, ok := ret.Get(0).(func(uint, ...string) *models.Customer); ok {
		r0 = rf(id, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, ...string) error); ok {
		r1 = rf(id, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: offset, limit
func (_m *CustomerRepository) List(offset int, limit int) ([]models.Customer, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Customer, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Customer); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWithPreloads provides a mock function with given fields: offset, limit, preloads
func (_m *CustomerRepository) ListWithPreloads(offset int, limit int, preloads ...string) ([]models.Customer, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, offset, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPreloads")
	}

	var r0 []models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, ...string) ([]models.Customer, error)); ok {
		return rf(offset, limit, preloads...)
	}
	if rf, ok := ret.Get(0).(func(int, int, ...string) []models.Customer); ok {
		r0 = rf(offset, limit, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, ...string) error); ok {
		r1 = rf(offset, limit, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: customer
func (_m *CustomerRepository) Update(customer *models.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func (_m *CustomerRepository) ListSortedWithPreloads(offset int, limit int, sortBy string, sortOrder string, preloads ...string) ([]models.Customer, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder, preloads)
	var r0 []models.Customer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Customer)
	}
	return r0, ret.Error(1)
}

func (_m *CustomerRepository) Search(query string, offset int, limit int, sortBy string, sortOrder string, preloads ...string) ([]models.Customer, error) {
	ret := _m.Called(query, offset, limit, sortBy, sortOrder, preloads)
	var r0 []models.Customer
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Customer)
	}
	return r0, ret.Error(1)
}

func (_m *CustomerRepository) CountSearch(query string) (int64, error) {
	ret := _m.Called(query)
	return ret.Get(0).(int64), ret.Error(1)
}

func (_m *CustomerRepository) WithTx(tx *gorm.DB) repository.CustomerRepository {
	_m.Called(tx)
	return _m
}

func NewCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
