// Code generated by mockery v2.53.4. DO NOT EDIT.
// Written by hand in the generated style, like the other service mocks.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// DealService is a mock type for the DealService type
type DealService struct {
	mock.Mock
}

// Create provides a mock function with given fields: deal, probability, actorID
func (_m *DealService) Create(deal *models.Deal, probability *int, actorID uint) error {
	ret := _m.Called(deal, probability, actorID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Deal, *int, uint) error); ok {
		r0 = rf(deal, probability, actorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *DealService) GetByID(id uint) (*models.Deal, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Deal
	if rf, ok := ret.Get(0).(func(uint) (*models.Deal, error)); ok {
		return rf(id)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.Deal)
	}
	return r0, ret.Error(1)
}

// Update provides a mock function with given fields: deal, probability, actorID
func (_m *DealService) Update(deal *models.Deal, probability *int, actorID uint) error {
	ret := _m.Called(deal, probability, actorID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Deal, *int, uint) error); ok {
		r0 = rf(deal, probability, actorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeStage provides a mock function with given fields: id, stage, probability, lostReason, actorID
func (_m *DealService) ChangeStage(id uint, stage models.DealStage, probability *int, lostReason *string, actorID uint) (*models.Deal, error) {
	ret := _m.Called(id, stage, probability, lostReason, actorID)

	if len(ret) == 0 {
		panic("no return value specified for ChangeStage")
	}

	var r0 *models.Deal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.Deal)
	}
	return r0, ret.Error(1)
}

// Delete provides a mock function with given fields: id
func (_m *DealService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	return ret.Error(0)
}

// List provides a mock function with given fields: offset, limit, filter
func (_m *DealService) List(offset int, limit int, filter repository.DealListFilter) ([]models.Deal, int64, error) {
	ret := _m.Called(offset, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Deal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Deal)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// ListByCompany provides a mock function with given fields: companyID, ownerID, offset, limit
func (_m *DealService) ListByCompany(companyID uint, ownerID *uint, offset int, limit int) ([]models.Deal, int64, error) {
	ret := _m.Called(companyID, ownerID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByCompany")
	}

	var r0 []models.Deal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Deal)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// ListByCustomer provides a mock function with given fields: customerID, ownerID, offset, limit
func (_m *DealService) ListByCustomer(customerID uint, ownerID *uint, offset int, limit int) ([]models.Deal, int64, error) {
	ret := _m.Called(customerID, ownerID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomer")
	}

	var r0 []models.Deal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Deal)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// History provides a mock function with given fields: dealID
func (_m *DealService) History(dealID uint) ([]models.DealStageChange, error) {
	ret := _m.Called(dealID)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 []models.DealStageChange
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.DealStageChange)
	}
	return r0, ret.Error(1)
}
