// Code generated by mockery v2.53.4. DO NOT EDIT.
// Written by hand in the generated style, like the other repository mocks.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.DealRepository = (*DealRepository)(nil)

// DealRepository is a mock type for the DealRepository type
type DealRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: deal
func (_m *DealRepository) Create(deal *models.Deal) error {
	ret := _m.Called(deal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Deal) error); ok {
		r0 = rf(deal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *DealRepository) GetByID(id uint) (*models.Deal, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Deal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.Deal)
	}
	return r0, ret.Error(1)
}

// Update provides a mock function with given fields: deal
func (_m *DealRepository) Update(deal *models.Deal) error {
	ret := _m.Called(deal)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	return ret.Error(0)
}

// Delete provides a mock function with given fields: id
func (_m *DealRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	return ret.Error(0)
}

// List provides a mock function with given fields: offset, limit, filter
func (_m *DealRepository) List(offset int, limit int, filter repository.DealListFilter) ([]models.Deal, int64, error) {
	ret := _m.Called(offset, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Deal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Deal)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}

// CreateStageChange provides a mock function with given fields: change
func (_m *DealRepository) CreateStageChange(change *models.DealStageChange) error {
	ret := _m.Called(change)

	if len(ret) == 0 {
		panic("no return value specified for CreateStageChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.DealStageChange) error); ok {
		r0 = rf(change)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListStageChanges provides a mock function with given fields: dealID
func (_m *DealRepository) ListStageChanges(dealID uint) ([]models.DealStageChange, error) {
	ret := _m.Called(dealID)

	if len(ret) == 0 {
		panic("no return value specified for ListStageChanges")
	}

	var r0 []models.DealStageChange
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.DealStageChange)
	}
	return r0, ret.Error(1)
}

// WithTx provides a mock function with given fields: tx
func (_m *DealRepository) WithTx(tx *gorm.DB) repository.DealRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.DealRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.DealRepository); ok {
		r0 = rf(tx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(repository.DealRepository)
	}

	return r0
}
