// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.LabelRepository = (*LabelRepository)(nil)

// LabelRepository is an autogenerated mock type for the LabelRepository type
type LabelRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: label
func (_m *LabelRepository) Create(label *models.Label) error {
	ret := _m.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Label) error); ok {
		r0 = rf(label)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *LabelRepository) GetByID(id uint) (*models.Label, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Label
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.Label)
	}
	return r0, ret.Error(1)
}

// Update provides a mock function with given fields: label
func (_m *LabelRepository) Update(label *models.Label) error {
	ret := _m.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	return ret.Error(0)
}

// Delete provides a mock function with given fields: id
func (_m *LabelRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	return ret.Error(0)
}

// List provides a mock function with no fields
func (_m *LabelRepository) List() ([]models.Label, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Label
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Label)
	}
	return r0, ret.Error(1)
}

// FindByIDs provides a mock function with given fields: ids
func (_m *LabelRepository) FindByIDs(ids []uint) ([]models.Label, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []models.Label
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Label)
	}
	return r0, ret.Error(1)
}

// ExistsByNameInsensitive provides a mock function with given fields: name, excludeID
func (_m *LabelRepository) ExistsByNameInsensitive(name string, excludeID uint) (bool, error) {
	ret := _m.Called(name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByNameInsensitive")
	}

	return ret.Get(0).(bool), ret.Error(1)
}

// WithTx provides a mock function with given fields: tx
func (_m *LabelRepository) WithTx(tx *gorm.DB) repository.LabelRepository {
	_m.Called(tx)
	return _m
}

// NewLabelRepository creates a new instance of LabelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLabelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LabelRepository {
	mock := &LabelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
