// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// The interface is deliberately NOT asserted here: internal/service's own
// in-package tests import this package, so importing service back would be an
// import cycle. The compile-time check lives in the handler tests instead.

// LabelService is an autogenerated mock type for the LabelService type
type LabelService struct {
	mock.Mock
}

// Create provides a mock function with given fields: label
func (_m *LabelService) Create(label *models.Label) error {
	ret := _m.Called(label)
	return ret.Error(0)
}

// GetByID provides a mock function with given fields: id
func (_m *LabelService) GetByID(id uint) (*models.Label, error) {
	ret := _m.Called(id)

	var r0 *models.Label
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*models.Label)
	}
	return r0, ret.Error(1)
}

// Update provides a mock function with given fields: label
func (_m *LabelService) Update(label *models.Label) error {
	ret := _m.Called(label)
	return ret.Error(0)
}

// Delete provides a mock function with given fields: id
func (_m *LabelService) Delete(id uint) error {
	ret := _m.Called(id)
	return ret.Error(0)
}

// List provides a mock function with no fields
func (_m *LabelService) List() ([]models.Label, error) {
	ret := _m.Called()

	var r0 []models.Label
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Label)
	}
	return r0, ret.Error(1)
}

// NewLabelService creates a new instance of LabelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLabelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LabelService {
	mock := &LabelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
