// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	repository "github.com/florinel-chis/gophercrm/internal/repository"
)

// PasswordResetTokenRepository is an autogenerated mock type for the PasswordResetTokenRepository type
type PasswordResetTokenRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: token
func (_m *PasswordResetTokenRepository) Create(token *models.PasswordResetToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PasswordResetToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTokenHash provides a mock function with given fields: tokenHash
func (_m *PasswordResetTokenRepository) GetByTokenHash(tokenHash string) (*models.PasswordResetToken, error) {
	ret := _m.Called(tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.PasswordResetToken, error)); ok {
		return rf(tokenHash)
	}
	if rf, ok := ret.Get(0).(func(string) *models.PasswordResetToken); ok {
		r0 = rf(tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkUsed provides a mock function with given fields: id
func (_m *PasswordResetTokenRepository) MarkUsed(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidateAllForUser provides a mock function with given fields: userID
func (_m *PasswordResetTokenRepository) InvalidateAllForUser(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpired provides a mock function with no fields
func (_m *PasswordResetTokenRepository) DeleteExpired() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *PasswordResetTokenRepository) WithTx(tx *gorm.DB) repository.PasswordResetTokenRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.PasswordResetTokenRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.PasswordResetTokenRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PasswordResetTokenRepository)
		}
	}

	return r0
}

// NewPasswordResetTokenRepository creates a new instance of PasswordResetTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordResetTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordResetTokenRepository {
	mock := &PasswordResetTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
