// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	repository "github.com/florinel-chis/gophercrm/internal/repository"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: token
func (_m *RefreshTokenRepository) Create(token *models.RefreshToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RefreshToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpired provides a mock function with no fields
func (_m *RefreshTokenRepository) DeleteExpired() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTokenHash provides a mock function with given fields: tokenHash
func (_m *RefreshTokenRepository) GetByTokenHash(tokenHash string) (*models.RefreshToken, error) {
	ret := _m.Called(tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.RefreshToken, error)); ok {
		return rf(tokenHash)
	}
	if rf, ok := ret.Get(0).(func(string) *models.RefreshToken); ok {
		r0 = rf(tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeAllForUser provides a mock function with given fields: userID
func (_m *RefreshTokenRepository) RevokeAllForUser(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeByTokenHash provides a mock function with given fields: tokenHash
func (_m *RefreshTokenRepository) RevokeByTokenHash(tokenHash string) error {
	ret := _m.Called(tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *RefreshTokenRepository) WithTx(tx *gorm.DB) repository.RefreshTokenRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.RefreshTokenRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.RefreshTokenRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RefreshTokenRepository)
		}
	}

	return r0
}

// GetByUserID provides a mock function with given fields: userID
func (_m *RefreshTokenRepository) GetByUserID(userID uint) ([]models.RefreshToken, error) {
	ret := _m.Called(userID)
	var r0 []models.RefreshToken
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.RefreshToken)
	}
	return r0, ret.Error(1)
}

// RevokeAllByUserID provides a mock function with given fields: userID
func (_m *RefreshTokenRepository) RevokeAllByUserID(userID uint) error {
	ret := _m.Called(userID)
	return ret.Error(0)
}

// DeleteByTokenHash provides a mock function with given fields: tokenHash
func (_m *RefreshTokenRepository) DeleteByTokenHash(tokenHash string) error {
	ret := _m.Called(tokenHash)
	return ret.Error(0)
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
