// Code generated by mockery v2.53.4. DO NOT EDIT.
// Modified to add missing interface methods.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.TaskRepository = (*TaskRepository)(nil)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// Count provides a mock function with no fields
func (_m *TaskRepository) Count() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByAssignedToID provides a mock function with given fields: assignedToID
func (_m *TaskRepository) CountByAssignedToID(assignedToID uint) (int64, error) {
	ret := _m.Called(assignedToID)

	if len(ret) == 0 {
		panic("no return value specified for CountByAssignedToID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (int64, error)); ok {
		return rf(assignedToID)
	}
	if rf, ok := ret.Get(0).(func(uint) int64); ok {
		r0 = rf(assignedToID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(assignedToID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountPending provides a mock function with no fields
func (_m *TaskRepository) CountPending() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountPending")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: task
func (_m *TaskRepository) Create(task *models.Task) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Task) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *TaskRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAssignedToID provides a mock function with given fields: assignedToID, offset, limit
func (_m *TaskRepository) GetByAssignedToID(assignedToID uint, offset int, limit int) ([]models.Task, error) {
	ret := _m.Called(assignedToID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignedToID")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Task, error)); ok {
		return rf(assignedToID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Task); ok {
		r0 = rf(assignedToID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(assignedToID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAssignedToIDWithPreloads provides a mock function with given fields: assignedToID, offset, limit, preloads
func (_m *TaskRepository) GetByAssignedToIDWithPreloads(assignedToID uint, offset int, limit int, preloads ...string) ([]models.Task, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, assignedToID, offset, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignedToIDWithPreloads")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int, ...string) ([]models.Task, error)); ok {
		return rf(assignedToID, offset, limit, preloads...)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int, ...string) []models.Task); ok {
		r0 = rf(assignedToID, offset, limit, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int, ...string) error); ok {
		r1 = rf(assignedToID, offset, limit, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TaskRepository) GetByID(id uint) (*models.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDWithPreloads provides a mock function with given fields: id, preloads
func (_m *TaskRepository) GetByIDWithPreloads(id uint, preloads ...string) (*models.Task, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithPreloads")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, ...string) (*models.Task, error)); ok {
		return rf(id, preloads...)
	}
	if rf, ok := ret.Get(0).(func(uint, ...string) *models.Task); ok {
		r0 = rf(id, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, ...string) error); ok {
		r1 = rf(id, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: offset, limit
func (_m *TaskRepository) List(offset int, limit int) ([]models.Task, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Task, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Task); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWithPreloads provides a mock function with given fields: offset, limit, preloads
func (_m *TaskRepository) ListWithPreloads(offset int, limit int, preloads ...string) ([]models.Task, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, offset, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPreloads")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, ...string) ([]models.Task, error)); ok {
		return rf(offset, limit, preloads...)
	}
	if rf, ok := ret.Get(0).(func(int, int, ...string) []models.Task); ok {
		r0 = rf(offset, limit, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, ...string) error); ok {
		r1 = rf(offset, limit, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: task
func (_m *TaskRepository) Update(task *models.Task) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Task) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func (_m *TaskRepository) ListSortedWithPreloads(offset int, limit int, sortBy string, sortOrder string, preloads ...string) ([]models.Task, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder, preloads)
	var r0 []models.Task
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Task)
	}
	return r0, ret.Error(1)
}

func (_m *TaskRepository) Search(query string, offset int, limit int, sortBy string, sortOrder string, preloads ...string) ([]models.Task, error) {
	ret := _m.Called(query, offset, limit, sortBy, sortOrder, preloads)
	var r0 []models.Task
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Task)
	}
	return r0, ret.Error(1)
}

func (_m *TaskRepository) CountSearch(query string) (int64, error) {
	ret := _m.Called(query)
	return ret.Get(0).(int64), ret.Error(1)
}

func (_m *TaskRepository) WithTx(tx *gorm.DB) repository.TaskRepository {
	_m.Called(tx)
	return _m
}

func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
