// Code generated by mockery v2.53.4. DO NOT EDIT.
// Modified to add missing interface methods.

package mocks

import (
	models "github.com/florinel-chis/gophercrm/internal/models"
	repository "github.com/florinel-chis/gophercrm/internal/repository"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

var _ repository.TicketRepository = (*TicketRepository)(nil)

// TicketRepository is an autogenerated mock type for the TicketRepository type
type TicketRepository struct {
	mock.Mock
}

// Count provides a mock function with no fields
func (_m *TicketRepository) Count() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByAssignedToID provides a mock function with given fields: assignedToID
func (_m *TicketRepository) CountByAssignedToID(assignedToID uint) (int64, error) {
	ret := _m.Called(assignedToID)

	if len(ret) == 0 {
		panic("no return value specified for CountByAssignedToID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (int64, error)); ok {
		return rf(assignedToID)
	}
	if rf, ok := ret.Get(0).(func(uint) int64); ok {
		r0 = rf(assignedToID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(assignedToID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByCustomerID provides a mock function with given fields: customerID
func (_m *TicketRepository) CountByCustomerID(customerID uint) (int64, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for CountByCustomerID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (int64, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(uint) int64); ok {
		r0 = rf(customerID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountOpen provides a mock function with no fields
func (_m *TicketRepository) CountOpen() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountOpen")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ticket
func (_m *TicketRepository) Create(ticket *models.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *TicketRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAssignedToID provides a mock function with given fields: assignedToID, offset, limit
func (_m *TicketRepository) GetByAssignedToID(assignedToID uint, offset int, limit int) ([]models.Ticket, error) {
	ret := _m.Called(assignedToID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignedToID")
	}

	var r0 []models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Ticket, error)); ok {
		return rf(assignedToID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Ticket); ok {
		r0 = rf(assignedToID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(assignedToID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAssignedToIDWithPreloads provides a mock function with given fields: assignedToID, offset, limit, preloads
func (_m *TicketRepository) GetByAssignedToIDWithPreloads(assignedToID uint, offset int, limit int, preloads ...string) ([]models.Ticket, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, assignedToID, offset, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignedToIDWithPreloads")
	}

	var r0 []models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int, ...string) ([]models.Ticket, error)); ok {
		return rf(assignedToID, offset, limit, preloads...)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int, ...string) []models.Ticket); ok {
		r0 = rf(assignedToID, offset, limit, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int, ...string) error); ok {
		r1 = rf(assignedToID, offset, limit, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCustomerID provides a mock function with given fields: customerID, offset, limit
func (_m *TicketRepository) GetByCustomerID(customerID uint, offset int, limit int) ([]models.Ticket, error) {
	ret := _m.Called(customerID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomerID")
	}

	var r0 []models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Ticket, error)); ok {
		return rf(customerID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Ticket); ok {
		r0 = rf(customerID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(customerID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCustomerIDWithPreloads provides a mock function with given fields: customerID, offset, limit, preloads
func (_m *TicketRepository) GetByCustomerIDWithPreloads(customerID uint, offset int, limit int, preloads ...string) ([]models.Ticket, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, customerID, offset, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomerIDWithPreloads")
	}

	var r0 []models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int, ...string) ([]models.Ticket, error)); ok {
		return rf(customerID, offset, limit, preloads...)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int, ...string) []models.Ticket); ok {
		r0 = rf(customerID, offset, limit, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int, ...string) error); ok {
		r1 = rf(customerID, offset, limit, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TicketRepository) GetByID(id uint) (*models.Ticket, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Ticket, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Ticket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDWithPreloads provides a mock function with given fields: id, preloads
func (_m *TicketRepository) GetByIDWithPreloads(id uint, preloads ...string) (*models.Ticket, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithPreloads")
	}

	var r0 *models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, ...string) (*models.Ticket, error)); ok {
		return rf(id, preloads...)
	}
	if rf, ok := ret.Get(0).(func(uint, ...string) *models.Ticket); ok {
		r0 = rf(id, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, ...string) error); ok {
		r1 = rf(id, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: offset, limit
func (_m *TicketRepository) List(offset int, limit int) ([]models.Ticket, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Ticket, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Ticket); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWithPreloads provides a mock function with given fields: offset, limit, preloads
func (_m *TicketRepository) ListWithPreloads(offset int, limit int, preloads ...string) ([]models.Ticket, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, offset, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPreloads")
	}

	var r0 []models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, ...string) ([]models.Ticket, error)); ok {
		return rf(offset, limit, preloads...)
	}
	if rf, ok := ret.Get(0).(func(int, int, ...string) []models.Ticket); ok {
		r0 = rf(offset, limit, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, ...string) error); ok {
		r1 = rf(offset, limit, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ticket
func (_m *TicketRepository) Update(ticket *models.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTicketRepository creates a new instance of TicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func (_m *TicketRepository) ListSortedWithPreloads(offset int, limit int, sortBy string, sortOrder string, preloads ...string) ([]models.Ticket, error) {
	ret := _m.Called(offset, limit, sortBy, sortOrder, preloads)
	var r0 []models.Ticket
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Ticket)
	}
	return r0, ret.Error(1)
}

func (_m *TicketRepository) Search(query string, offset int, limit int, sortBy string, sortOrder string, preloads ...string) ([]models.Ticket, error) {
	ret := _m.Called(query, offset, limit, sortBy, sortOrder, preloads)
	var r0 []models.Ticket
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Ticket)
	}
	return r0, ret.Error(1)
}

func (_m *TicketRepository) CountSearch(query string) (int64, error) {
	ret := _m.Called(query)
	return ret.Get(0).(int64), ret.Error(1)
}

func (_m *TicketRepository) WithTx(tx *gorm.DB) repository.TicketRepository {
	_m.Called(tx)
	return _m
}

func NewTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepository {
	mock := &TicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
