// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/florinel-chis/gocrm/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// TicketService is an autogenerated mock type for the TicketService type
type TicketService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ticket
func (_m *TicketService) Create(ticket *models.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *TicketService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAssignee provides a mock function with given fields: assigneeID, offset, limit
func (_m *TicketService) GetByAssignee(assigneeID uint, offset int, limit int) ([]models.Ticket, int64, error) {
	ret := _m.Called(assigneeID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignee")
	}

	var r0 []models.Ticket
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Ticket, int64, error)); ok {
		return rf(assigneeID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Ticket); ok {
		r0 = rf(assigneeID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) int64); ok {
		r1 = rf(assigneeID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, int, int) error); ok {
		r2 = rf(assigneeID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByCustomer provides a mock function with given fields: customerID, offset, limit
func (_m *TicketService) GetByCustomer(customerID uint, offset int, limit int) ([]models.Ticket, int64, error) {
	ret := _m.Called(customerID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomer")
	}

	var r0 []models.Ticket
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Ticket, int64, error)); ok {
		return rf(customerID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Ticket); ok {
		r0 = rf(customerID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) int64); ok {
		r1 = rf(customerID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, int, int) error); ok {
		r2 = rf(customerID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *TicketService) GetByID(id uint) (*models.Ticket, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Ticket, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Ticket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: offset, limit
func (_m *TicketService) List(offset int, limit int) ([]models.Ticket, int64, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Ticket
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Ticket, int64, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Ticket); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ticket
func (_m *TicketService) Update(ticket *models.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTicketService creates a new instance of TicketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketService {
	mock := &TicketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
