// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *TransactionManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTransactionAndRetry provides a mock function with given fields: ctx, fn, maxRetries
func (_m *TransactionManager) WithTransactionAndRetry(ctx context.Context, fn func(context.Context) error, maxRetries int) error {
	ret := _m.Called(ctx, fn, maxRetries)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error, int) error); ok {
		r0 = rf(ctx, fn, maxRetries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTransactionManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionManager(t mockConstructorTestingTNewTransactionManager) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}